import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function CategoriesLayout({ children }: { children: React.ReactNode }) {
	return <main className="flex min-h-screen flex-col items-start justify-start p-16">{children}</main>;
}
