import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<nav className="p-4 font-bold bg-[#14281d] text-[#c2a878] dark:bg-[#c2a878] dark:text-[#14281d]">
					<ol className="font-light flex flex-col sm:flex-row items-center justify-between">
						<li>
							<Link href={"/"}>
								<div id="logo" className="font-extrabold">
									Pleasant Hollow
								</div>
							</Link>
						</li>
						<li>
							<Link href="/">Home</Link>
						</li>
						<li>
							<Link href="/">Categories</Link>
						</li>
						<li>
							<Link href="/">?</Link>
						</li>
					</ol>
				</nav>
				{children}
			</body>
		</html>
	);
}
